packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  # Core dependencies
  react: "^19.1.1"
  react-dom: "^19.1.1"
  next: "^15.1.0"
  typescript: "5.7.3"
  
  # Common libraries
  lodash: "^4.17.21"
  zod: "^3.24.3"
  "react-hook-form": "^7.62.0"
  "better-auth": "^1.2.7"
  superjson: "^2.2.1"
  "react-router": "^7.9.1"
  "react-error-boundary": "^6.0.0"
  "react-dropzone": "^14.3.8"

  # Tanstack
  "@tanstack/react-query": "^5.89.0"
  "@tanstack/react-query-persist-client": "^5.75.2"

  # UI & Styling
  "class-variance-authority": "^0.7.0"
  "clsx": "^2.1.1"
  "tailwind-merge": "^2.5.4"
  "tailwindcss": "^4.1.13"
  "@tailwindcss/vite": "^4.1.13"
  "tailwindcss-animate": "^1.0.7"
  "tailwind-scrollbar-hide": "^4.0.0"
  "@pyncz/tailwind-mask-image": "^2.0.0"
  "@tailwindcss/container-queries": "^0.1.1"
  "@tailwindcss/postcss": "4.1.11"
  "@tailwindcss/typography": "^0.5.12"
  "postcss": "^8.4.38"
  "lucide-react": "^0.477.0"
  "tw-animate-css": "^1.1.0"
  "next-themes": "0.4.6"
  autoprefixer: "^10.4.20"

  # Development Tools
  "eslint": "^9.33.0"
  "@eslint/js": "9.33.0"
  "@eslint/eslintrc": "^3.2.0"
  "prettier": "^3.4.2"
  "prettier-plugin-tailwindcss": "^0.6.11"
  "@vitejs/plugin-react-swc": "^4.0.0"
  vite: "^7.1.2"

  # Utilities
  "js-cookie": "^3.0.5"

  # Types
  "@types/react": "19.2.0"
  "@types/react-dom": "19.2.0"
  "@types/node": "^24.5.0"
  "@types/lodash": "^4.17.16"
  "@types/js-cookie": "^3.0.6"
