services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - database
      - redis
      - mail
      - minio
    command: >
      sh -c "pnpm start:dev"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - database
      - redis
      - minio
    command: >
      sh -c "pnpm start:dev"

  database:
    image: postgres:16
    container_name: ai-tracker-back-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
      TZ: 'UTC'
    ports:
      - '${DOCKER_DATABASE_PORT}:5432'
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data
    networks:
      - ai-tracker-back-network

  mail:
    image: axllent/mailpit:v1.25
    container_name: ai-tracker-back-mail
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${DOCKER_MAIL_PORT}:1025
      - ${DOCKER_MAIL_CLIENT_PORT}:8025
    networks:
      - ai-tracker-back-network
      
  minio:
    image: minio/minio:latest
    container_name: ai-tracker-back-minio
    restart: unless-stopped
    ports:
      - '${DOCKER_MINIO_API_PORT:-9000}:9000'
      - '${DOCKER_MINIO_CONSOLE_PORT:-9001}:9001'
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER:-minioadmin}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD:-minioadmin}'
    volumes:
      - ./.docker/minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ai-tracker-back-network
